app/Http/Controllers/AccountHistory.php, database/seeders/PermissionsSeeder.php, public/build/manifest.json, resources/js/Helpers/MenuItems.js, resources/js/Layouts/AppLayout.vue, resources/js/Pages/AccountHistory/Show.vue, resources/js/Pages/Category/Show.vue, routes/web.php
- [ x] Feature
- Lista las cuentas por cobrar 
- ir a: {server}/dashboard/account-history
=> feature/PDSL-141: Permitir listar las cuentas por cobrar - Backend

app/Http/Controllers/AccountHistory.php, database/seeders/PermissionsSeeder.php, public/build/manifest.json, resources/js/Helpers/MenuItems.js, resources/js/Layouts/AppLayout.vue, resources/js/Pages/AccountHistory/Show.vue, resources/js/Pages/Category/Show.vue, routes/web.php
- Define los roles y permisos 
- php artisan migrate:refresh --seed
=> Feature/PDSL-134: Definir roles y permisos - Backend 

public/build/manifest.json, resources/js/Pages/AccountHistory/Show.vue
=> Feature/PDSL-140: Permitir listar las cuentas por cobrar - Frontend

app/Http/Controllers/PresaleController.php, resources/js/Pages/Presale/Show.vue, resources/scss/main.scss
=> Feature/PDSL-143: Permitir filtrar pedidos - Backend/Frontend

app/Http/Controllers/ArticleController.php
- Agregar funcionalidad de cambiar el precio de venta a todas las entradas en estock de un mismo producto
- En vista editar producto o articulo, colocar un campo con nombre globalPrice
=> Feature/PDSL-150 Permitir cambiar el precio del producto - Backend

app/Http/Controllers/ArticleController.php, public/build/manifest.json, resources/js/Components/Article/Detail.vue, resources/js/Pages/Article/Show.vue
=> Feature/PDSL-149: Permitir cambiar el precio del producto - Frontend 

app/Http/Controllers/AccountHistory.php, public/build/manifest.json, resources/js/Components/DropdownLink.vue, resources/js/Helpers/MenuItems.js, resources/js/Layouts/AppLayout.vue, resources/js/Pages/AccountHistory/Show.vue
=> Feature/PDSL-148: Permitir filtrar las cuentas por cobrar - Backend / Frontend

.gitignore, app/Http/Controllers/PresaleController.php, package-lock.json, public/build/manifest.json
- Implementa lógica de descargo de artículos de stock si el pedido se marca como entregado
- En la lista de pedidos se excluyen los pedidos que están marcados como entregados
- ir a editar un pedido y marcarlo como entregado
=> feature/PDSL-144: Permitir asignar estados de pedidos - Backend

.gitignore, app/Http/Controllers/PresaleController.php, app/Http/Resources/StockDetailArticle.php, package-lock.json, public/build/manifest.json, resources/js/Components/Presale/Detail.vue, resources/js/Components/Presale/PresaleForm.vue, resources/js/Pages/Presale/Show.vue, resources/js/Pages/Stock/Show.vue, resources/js/Pages/Suppliers/Show.vue
=> Feature/PDSL-126: Permitir asignar estados de pedidos - Frontend

database/seeders/PresaleSeeder.php, package-lock.json, package.json, resources/js/Components/Charts/LineChart.vue, resources/js/Components/Shared/Pagination.vue, resources/js/Components/User/DeleteUser.vue, resources/js/Helpers/MenuItems.js, resources/js/Pages/AccountHistory/Show.vue, resources/js/Pages/Article/Show.vue, resources/js/Pages/Category/Show.vue, resources/js/Pages/Clients/Show.vue, resources/js/Pages/Dashboard.vue, resources/js/Pages/Measure/Show.vue, resources/js/Pages/Presale/Show.vue, resources/js/Pages/Stock/Show.vue, resources/js/Pages/Suppliers/Show.vue, resources/js/app.js, resources/scss/main.scss
- Mejora en la pagina (UI y funcionamiento)
- Evitar reset de datos
- Mejoras de interfaz
EVIDENCIA
- Instalar dependencias: ´npm install´
- Probar cualquier vista que tenga paginacion activa ( Example: Preventas)
=> Bugfix/PDSL-161: Error en paginacion de listados - Frontend

app/Http/Controllers/ClientController.php, package-lock.json
- [ X] Feature
- Registra una Cuenta por cobrar 
- Editar un cliente y agregar campo mount
=> feature/PDSL-155: Permitir agregar las cuentas pendientes de cobro - Backend

app/Http/Controllers/ClientController.php, app/Http/Controllers/PresaleController.php, app/Http/Resources/Presale.php, app/Models/Presale.php, database/migrations/2022_09_02_201016_create_presales_table.php, package-lock.json, resources/js/Assets/images/tilt.svg, resources/js/Components/AuthenticationCard.vue, resources/js/Components/Charts/LineChart.vue, resources/js/Components/Checkbox.vue, resources/js/Components/Presale/Detail.vue, resources/js/Components/Presale/PresaleForm.vue, resources/js/Components/Shared/Pagination.vue, resources/js/Components/Shared/Toggle.vue, resources/js/Helpers/MenuItems.js, resources/js/Pages/AccountHistory/Show.vue, resources/js/Pages/Auth/ForgotPassword.vue, resources/js/Pages/Clients/Show.vue, resources/js/Pages/Dashboard.vue, resources/js/Pages/Presale/Show.vue, resources/scss/main.scss
=> Feature/PDSL-156: Permitir agregar las cuentas pendientes de cobro - Frontend

app/Http/Controllers/PresaleController.php, resources/js/Components/Presale/Detail.vue, resources/js/Components/Presale/PresaleForm.vue, resources/js/Components/Table.vue, resources/js/Helpers/MenuItems.js, resources/js/Pages/AccountHistory/Show.vue, resources/js/Pages/Article/Show.vue, resources/js/Pages/Category/Show.vue, resources/js/Pages/Clients/Show.vue, resources/js/Pages/Express/Create.vue, resources/js/Pages/Express/Show.vue, resources/js/Pages/Measure/Show.vue, resources/js/Pages/Presale/Show.vue, resources/js/Pages/Stock/Detail.vue, resources/js/Pages/Stock/Show.vue, resources/js/Pages/Suppliers/Show.vue, resources/js/Pages/User/Show.vue, routes/web.php
=> Feature/PDSL-154: Crear y listar ventas Express - Frontend

app/Http/Controllers/AccountHistory.php, app/Models/HistoryPayment.php, database/migrations/2022_11_10_024118_create_history_payments_table.php, package-lock.json, routes/web.php
- Agrega historial de abonos a preventa
- EP: dashboard/history-payment
- Acepta el id de la preventa y el monto a abonar
=> feature/PDSL-159: Permitir abonar cuenta por cobrar - Backend

app/Http/Controllers/AccountHistory.php, resources/js/Components/Presale/Detail.vue, resources/js/Helpers/MenuItems.js, resources/js/Pages/AccountHistory/Show.vue, resources/scss/main.scss, routes/web.php, tailwind.config.js
=> Feature/PDSL-158: Permitir abonar cuenta por cobrar - Frontend

app/Http/Controllers/AccountHistory.php, app/Http/Controllers/PresaleController.php, routes/web.php
- Filtra las preventas en sus diferentes estados
- Ir al apartado de cuentas por cobrar
=> feature/PDSL-162: Listar historial de ventas - Backend

app/Http/Controllers/DashboardController.php, app/Models/Client.php
- devuelve el array del top articulos crrectamente
- v1 de top clientes
-....
=> feature/PDSL-157: top articulos, top clientes - en construcción

app/Http/Controllers/DashboardController.php, package-lock.json, resources/js/Components/Charts/LineChart.vue, resources/js/Components/Dashboard/CardPreview.vue, resources/js/Pages/Dashboard.vue
=> Feature/PDSL-11: Mostrar vista general - Frontend

app/Http/Controllers/DashboardController.php, app/Models/Client.php, routes/web.php
- retorna los datos necesarios para vista dashboard
- ir a home
=> Feature/PDSL-157: Mostrar vista general - Backend

app/Http/Controllers/DashboardController.php, resources/js/Components/Charts/LineChart.vue, resources/js/Pages/Dashboard.vue
- [] Refactorizando (sin cambios funcionales, sin cambios de API)
- retorna de mejor manera la data para las gráficas
- ir a home
=> feature/PDSL-11: mejorando data de gráficos

resources/js/Pages/Profile/Show.vue, resources/js/Pages/User/Show.vue
=> Feature/PDSL-11: Mostrar vista general - Frontend	

resources/views/app.blade.php
=> fix(feature/PDSL-11) Agregar meta

app/Http/Controllers/CategoryArticleController.php, resources/js/Pages/Dashboard.vue
=> fix(feature/PDSL-11) Remover evento

app/Http/Controllers/DashboardController.php
=> fix(feature/PDSL-11) Corregir validation

app/Http/Controllers/PresaleController.php, app/Http/Requests/StorePresaleRequest.php, app/Http/Requests/UpdatePresaleRequest.php, app/Http/Resources/Presale.php, app/Models/Presale.php, database/migrations/2022_09_02_201016_create_presales_table.php, resources/js/Components/Presale/Detail.vue, resources/js/Components/Presale/PresaleForm.vue, resources/js/Pages/AccountHistory/Show.vue, resources/js/Pages/Express/Create.vue, resources/js/Pages/Express/Show.vue
=> Bugfix/PDSL-167: Error total de abonos

resources/js/Components/Shared/Sidebar.vue, resources/js/Helpers/MenuItems.js, resources/js/Pages/Dashboard.vue, resources/js/Pages/Profile/Show.vue
=> Bugfix/PDSL-168:Mejoras UI y funcionalidades del sidebar
